version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/install_env.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
