spring:
  profiles:
    active: local

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: 6379

jwt:
  refresh-expiration-time: 2592000000 # 30일
  access-expiration-time: 3600000 # 1시간
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT_SECRET}
---
spring:
  config:
    activate:
      on-profile: dev

debug: true
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3307/bamdoliro_maru
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bamdoliro
    password: bamdoliro

  data:
    redis:
      host: localhost
      password: bamdoliro

server:
  port: 8088

debug: true
