spring:
  profiles:
    active: local

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      stack:
        auto: false
      region:
        static: ${S3_REGION}
      credentials:
        instance-profile: true
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}

  logging:
    level:
      com.amazonaws.util.EC2MetadataUtils: error

jwt:
  refresh-expiration-time: 1296000000 # 15일
  access-expiration-time: 3600000 # 1시간
  prefix: Bearer
  secret-key: ${JWT_SECRET}

neis:
  key: ${NEIS_KEY}
---
spring:
  config:
    activate:
      on-profile: prod

  web:
    resources:
      add-mappings: false
---
spring:
  config:
    activate:
      on-profile: dev

debug: true
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/maru
    driver-class-name: org.postgresql.Driver
    username: bamdoliro
    password: bamdoliro

  data:
    redis:
      host: localhost
      port: 6379
      password: bamdoliro

debug: true
