spring:
  profiles:
    active: local

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: 6379

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  refresh-expiration-time: 1296000000 # 15일
  access-expiration-time: 3600000 # 1시간
  prefix: Bearer
  secret-key: ${JWT_SECRET}

neis:
  key: ${NEIS_KEY}
---
spring:
  config:
    activate:
      on-profile: dev

debug: true
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/maru
    driver-class-name: org.postgresql.Driver
    username: bamdoliro
    password: bamdoliro

  data:
    redis:
      host: localhost
      password: bamdoliro

server:
  port: 8088

debug: true
