name: Deploy to cloudtype

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ${{ secrets.CLOUDTYPE_PROJECT }}
          stage: main
          yaml: >
            name: maru

            app: dockerfile

            options:
              ports: 8080
              dockerfile: Dockerfile.dev
              env:
                - name: DB_NAME
                  value: ${{ secrets.DEV_DB_NAME }}
                - name: DB_USERNAME
                  value: ${{ secrets.DEV_DB_USERNAME }}
                - name: DB_HOST
                  value: ${{ secrets.DEV_DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.DEV_DB_PORT }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DEV_DB_PASSWORD }}
                - name: JWT_SECRET
                  value: ${{ secrets.DEV_JWT_SECRET }}
                - name: MESSAGE_API_KEY
                  value: ${{ secrets.MESSAGE_API_KEY }}
                - name: MESSAGE_API_SECRET
                  value: ${{ secrets.MESSAGE_API_SECRET }}
                - name: MESSAGE_API_DOMAIN
                  value: ${{ secrets.MESSAGE_API_DOMAIN }}
                - name: MESSAGE_FROM
                  value: ${{ secrets.MESSAGE_FROM }}
                - name: REDIS_HOST
                  value: ${{ secrets.DEV_REDIS_HOST }}
                - name: REDIS_PORT
                  value: ${{ secrets.DEV_REDIS_PORT }}
                - name: REDIS_PASSWORD
                  value: ${{ secrets.DEV_REDIS_PASSWORD }}
                - name: NEIS_KEY
                  value: ${{ secrets.DEV_NEIS_KEY }}
                - name: BUCKET_NAME 
                  value: ${{ secrets.BUCKET_NAME }}
                - name: S3_REGION
                  value: ${{ secrets.S3_REGION }}
                - name: S3_ACCESS_KEY
                  value: ${{ secrets.S3_ACCESS_KEY }}
                - name: S3_SECRET_KEY
                  value: ${{ secrets.S3_SECRET_KEY }}
                - name: TZ
                  value: Asia/Seoul
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: dockerfile