# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
  ENCRYPTION_SALT: ${{ secrets.ENCRYPTION_SALT }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  NEIS_KEY: ${{ secrets.NEIS_KEY }}
  MESSAGE_API_KEY: ${{ secrets.MESSAGE_API_KEY }}
  MESSAGE_API_SECRET: ${{ secrets.MESSAGE_API_SECRET }}
  MESSAGE_API_DOMAIN: ${{ secrets.MESSAGE_API_DOMAIN }}
  MESSAGE_FROM: ${{ secrets.MESSAGE_FROM }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6
    - name: Start localstack
      uses: LocalStack/setup-localstack@v0.2.3
      with:
        image-tag: "3.8.1"
        services: s3
      env:
        LOCALSTACK_AUTH_TOKEN: ${{secrets.LOCAL_STACK_SECRET_KEY}}
    - name: Create s3 Bucket
      run: awslocal s3 mb s3://maru-s3-test-bucket
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build --build-cache